### PR TITLE
:bug: Prevent adapter from connecting to search

### LINKED ISSUE #60: Disable ES index off Asynchronous event logs
Hi 
First off all great work on this package it's really powerful! 

We are getting some errors on the indexing off Asynchronous events to ES. Because we are using the Elasticsuite module for Elastic Search indexing the default ES client is not configured. 

I know there is a configuration option to enable / disable indexing, however disabling the indexing still triggers the error. Would there be any way around to completely remove the event indexing or make it compatible with elasticsuite module ? 

Thanks.

### PR DESCRIPTION
**Pull request by gowrizrh**
The classes DI injected into the indexer action class contain the elasticsearch adapter `\Magento\Elasticsearch\Model\Adapter\Elasticsearch` which attempts to connect to the configured search engine when the object manager attempts to create it.

However, in cases where elasticsearch is not used it causes a problem as the class that's requiring it also fails instantiation as described in #60 

Ideally, this class shouldn't fail from being created so that the indexer is able to skip it when set in the admin.

### CODE REVIEW

**Review by brettlaishley — APPROVED** [review]
LGTM

**Review by aligent-lturner — APPROVED** [review]

File: Model/Indexer/LuceneSearch.php [hunk 1]
```diff
@@ -49,35 +52,51 @@ public function __construct(
...
+            }
 
-            if (!empty($asyncEventIds)) {
-                $filter = $this->filterBuilder->setConditionType('in')
-                    ->setField($this->getName())
-                    ->setValue($asyncEventIds)
-                    ->create();
+            $this->getContext()->getDataProvider()->addFilter($filter->create());
+        } else {
+            if ((string)$value !== '') {
```
Comment (aligent-lturner) [inline Model/Indexer/LuceneSearch.php]: `$value` is a request parameter, which means that in theory, it could be an array (e.g. `https://store.com/results?search[]=123&search[]=456`).
Now, I'm assuming this will rarely (if ever) happen, but just a little wary of the practice.
Could this be `if (!empty($value))` instead?

File: Model/Indexer/LuceneSearch.php [hunk 2]
```diff
@@ -49,35 +52,51 @@ public function __construct(
...
-            );
+        if ($this->asyncEventsConfig->isIndexingEnabled()) {
+            $client = $this->connectionManager->getConnection();
+            $indexPrefix = $this->config->getIndexPrefix();
+            $filter = $this->filterBuilder->setConditionType('in')
+                ->setField($this->getName());
 
-            $rawDocuments = $rawResponse['hits']['hits'] ?? [];
-            $asyncEventIds = array_column($rawDocuments, '_id');
+            if ($value === "") {
```
Comment (aligent-lturner) [inline Model/Indexer/LuceneSearch.php]: I'd suggest checking for `empty` instead

File: Model/Indexer/LuceneSearch.php [hunk 3]
```diff
@@ -49,35 +52,51 @@ public function __construct(
...
-            $rawResponse = $client->query(
-                [
-                    'index' => $indexPrefix . '_async_event_*',
-                    'q' => $value,
-                    // the default page size is 10. The highest limit is 10000. If we want to traverse further, we will
-                    // have to use the search after parameter. There are no plans to implement this right now.
-                    'size' => 100
-                ]
-            );
+        if ($this->asyncEventsConfig->isIndexingEnabled()) {
```
Comment (aligent-lturner) [inline Model/Indexer/LuceneSearch.php:61]: In both the `if` and the `else` cases, you're only doing anything if `$value` is not empty. I'd suggest taking that out as an early return condition:
```
if (empty($value)) {
    return;
}

if ($this->asyncEventsConfig->isIndexingEnabled()) {
    // lucene search
} else {
    // apply basic 'like' filter
}
```

Comment (gowrizrh) [reply Model/Indexer/LuceneSearch.php:61]: i've updated as suggested :+1:

**Review by brettlaishley — APPROVED** [review]
Additional changes LGTM

**Review by aligent-lturner — APPROVED** [review]
